name: rl-va
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - ipython
  - jupyter_client
  - jupyter_core
  - matplotlib-inline
  - nest-asyncio
  - packaging
  - parso
  - pexpect
  - pickleshare
  - pillow
  - platformdirs
  - prompt-toolkit
  - psutil
  - ptyprocess
  - pygments
  - python-dateutil
  - pyzmq
  - setuptools
  - six
  - stack_data
  - tornado
  - traitlets
  - typing_extensions
  - wheel
  - zipp
  - pip:
      - cloudpickle==3.1.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - farama-notifications==0.0.4
      - filelock==3.20.0
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - gymnasium==1.2.2
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - minigrid==3.0.0
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - pandas==2.3.3
      - pygame==2.6.1
      - pyparsing==3.2.5
      - pytz==2025.2
      - stable-baselines3==2.7.0
      - sympy==1.14.0
      - torch==2.9.0
      - tqdm==4.67.1